tasks:
  - before: |
      curl -sfL gpm.simonemms.com | bash

      gpm install kubectl helm faas-cli
    command: kubectl port-forward -n openfaas svc/gateway 8080:8080
  - command: |
      # Install commitlint
      npm i -g @commitlint/{config-conventional,cli}

      # Install husky
      npm i -g husky

      # Activate hooks
      husky install

      # Copy .cobra.yaml to $HOME
      cp .cobra.yaml $HOME/.cobra.yaml

      if [ ! -f "go.mod" ]; then
        echo "Creating Go module"
        go mod init ${GITPOD_WORKSPACE_CONTEXT_URL/https:\/\//}
      fi
      if [ ! -f "main.go" ]; then
        echo "Create Cobra project"
        cobra-cli init
        go mod tidy
      fi

      make install_openfaas

      export OPENFAAS_USER=$(kubectl get secrets -n openfaas basic-auth -o jsonpath='{.data.basic-auth-user}' | base64 -d)
      export OPENFAAS_PASSWORD=$(kubectl get secrets -n openfaas basic-auth -o jsonpath='{.data.basic-auth-password}' | base64 -d)

      faas login -u $OPENFAAS_USER -p $OPENFAAS_PASSWORD

      make run
    init: |
      go install github.com/spf13/cobra-cli@latest

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - golang.go
    - ms-kubernetes-tools.vscode-kubernetes-tools

ports:
  - port: 8080
    visibility: private
    onOpen: notify
